{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-node-state.serviceAccountName" . }}
  labels:
    {{- include "kube-node-state.labels" . | nindent 4 }}  
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - watch
      - list
  {{- end }}